### ISSUE TITLE
{"- (1): Expected token type NEWLINE, but saw ID."}

### ISSUE THREAD

**Issue by bulutkartal** [uxmal/pytocs#10]
When I open the project in visual studio and try to run the command 'pytocs hello.py' i get an exception.

 at Pytocs.Syntax.Parser.Expect(TokenType tokenType) in C:\Users\b\Downloads\pytocs-master\pytocs-master\src\Syntax\Parser.cs:line 460
   at Pytocs.Syntax.Parser.simple_stmt() in C:\Users\b\Downloads\pytocs-master\pytocs-master\src\Syntax\Parser.cs:line 822
   at Pytocs.Syntax.Parser.stmt() in C:\Users\b\Downloads\pytocs-master\pytocs-master\src\Syntax\Parser.cs:line 792
   at Pytocs.Syntax.Parser.<Parse>d__4.MoveNext() in C:\Users\b\Downloads\pytocs-master\pytocs-master\src\Syntax\Parser.cs:line 336
   at Pytocs.Translate.ModuleTranslator.Translate(IEnumerable`1 statements) in C:\Users\b\Downloads\pytocs-master\pytocs-master\src\Translate\ModuleTranslator.cs:line 42
   at Pytocs.Translator.TranslateModuleStatements(IEnumerable`1 stm, State moduleScope, TextWriter output) in C:\Users\b\Downloads\pytocs-master\pytocs-master\src\Translator.cs:line 78
   at Pytocs.Translator.Translate(String filename, TextReader input, TextWriter output) in C:\Users\b\Downloads\pytocs-master\pytocs-master\src\Translator.cs:line 55
   at Pytocs.Program.Main(String[] args) in C:\Users\b\Downloads\pytocs-master\pytocs-master\src\Program.cs:line 37

**Comment by uxmal** [comment]
I'm not seeing this error on the `hello.py` in `subjects`. Can you try again with the commits from this week?

**Comment by bulutkartal** [comment]
![untitled](https://user-images.githubusercontent.com/16744466/36066344-72259d9c-0e6d-11e8-9793-f62e235a35d8.png)
