### ISSUE TITLE
pytocs pythonfilename.py

### ISSUE THREAD

**Issue by Essa999khan** [uxmal/pytocs#27]
pytocs GrayScale.py

Unhandled Exception: System.InvalidOperationException: -(1): Expected token type NEWLINE, but saw ID.
   at Pytocs.Syntax.Parser.Error(String str) in D:\pytocs-master\src\Syntax\Parser.cs:line 370
   at Pytocs.Syntax.Parser.Expect(TokenType tokenType) in D:\pytocs-master\src\Syntax\Parser.cs:line 461
   at Pytocs.Syntax.Parser.simple_stmt() in D:\pytocs-master\src\Syntax\Parser.cs:line 826
   at Pytocs.Syntax.Parser.stmt() in D:\pytocs-master\src\Syntax\Parser.cs:line 790
   at Pytocs.Syntax.Parser.<Parse>d__4.MoveNext() in D:\pytocs-master\src\Syntax\Parser.cs:line 337
   at Pytocs.Translate.ModuleTranslator.Translate(IEnumerable`1 statements) in D:\pytocs-master\src\Translate\ModuleTranslator.cs:line 42
   at Pytocs.Translator.TranslateModuleStatements(IEnumerable`1 stm, State moduleScope, TextWriter output) in D:\pytocs-master\src\Translator.cs:line 87
   at Pytocs.Translator.Translate(String filename, TextReader input, TextWriter output) in D:\pytocs-master\src\Translator.cs:line 56
   at Pytocs.Program.Main(String[] args) in D:\pytocs-master\src\Program.cs:line 37

**Comment by uxmal** [comment]
Thanks for the report. Without access to the actual file `GrayScale.py`, there really isn't much I can do. Either provide me with the complete file, or try reducing `GrayScale.py` to be as small as possible, then add it to this issue.

**Comment by uxmal** [comment]
Closing this due to lack of response.
