### ISSUE TITLE
Shift+Enter crashes pytocs

### ISSUE THREAD

**Issue by javskd2** [uxmal/pytocs#31]
Hitting Shift+Enter in pytocs crashes it with this error:

```
Unhandled Exception: System.InvalidOperationException: -(2): Expected token type ID, but saw NEWLINE.
  at Pytocs.Syntax.Parser.Error(String str) in C:\projects\pytocs\src\Syntax\Parser.cs:line 375
  at Pytocs.Syntax.Parser.Expect(TokenType tokenType) in C:\projects\pytocs\src\Syntax\Parser.cs:line 466
  at Pytocs.Syntax.Parser.funcdef() in C:\projects\pytocs\src\Syntax\Parser.cs:line 516
  at Pytocs.Syntax.Parser.compound_stmt() in C:\projects\pytocs\src\Syntax\Parser.cs:line 1333
  at Pytocs.Syntax.Parser.stmt() in C:\projects\pytocs\src\Syntax\Parser.cs:line 796
  at Pytocs.Syntax.Parser.<Parse>d__4.MoveNext() in C:\projects\pytocs\src\Syntax\Parser.cs:line 342
  at Pytocs.Translate.ModuleTranslator.Translate(IEnumerable`1 statements) in C:\projects\pytocs\src\Translate\ModuleTranslator.cs:line 41
  at Pytocs.Translator.TranslateModuleStatements(IEnumerable`1 stm, TypeReferenceTranslator types, TextWriter output) in C:\projects\pytocs\src\Translator.cs:line 99
  at Pytocs.Translator.Translate(String filename, TextReader input, TextWriter output) in C:\projects\pytocs\src\Translator.cs:line 58
  at Pytocs.Program.Main(String[] args) in C:\projects\pytocs\src\Program.cs:line 39
```

The program then stops responding and gets forcefully shutdown by windows.

**Comment by uxmal** [comment]
`pytocs` does expect correctly formatted Python program - it will throw up its hands if it cannot parse what is passed to it. Having said that, I tried running `pytocs` without any command line parameters, which makes it read its input from `stdin`. After hitting shift+Enter, I'm greeted with this on `stdout`:
```
public static class module_name {
}
```
after which it terminates and control returns to the shell.

Could you provide more details on how you are starting `pytocs`?

**Comment by javskd2** [comment]
I think i just ran it incorrectly. I downloaded the executable and ran it, then tried to run pytocs in the executable. Later i tried to run the windows command prompt and use pytocs, and it worked.
