### ISSUE TITLE
Unpacking **kwargs onto a new dictionary

### ISSUE THREAD

**Issue by Nucs** [uxmal/pytocs#57]
The following code fails due to the `**kwargs`
``` python
def funcy(*args, **kwargs):
  dictionary = {'a': 'str', **kwargs}	
  dictionary_inside_tuple = (1,{'a': 'str', **kwargs})
  return dictionary

print(funcy(key='value'))

```
output:
`{'a': 'str', 'key': 'value'}`

Exception:
```
Unhandled Exception: System.InvalidOperationException: C:\Users\Eli-PC\Desktop\pytocs\this\common\vec_env\subproc_vec_env.py(2): Expected token type RBRACE but saw OP_STARSTAR.
   at Pytocs.Core.Syntax.Parser.Error(String str, Object[] args)
   at Pytocs.Core.Syntax.Parser.Expect(TokenType tokenType)
   at Pytocs.Core.Syntax.Parser.atom()
   at Pytocs.Core.Syntax.Parser.atom_expr()
   at Pytocs.Core.Syntax.Parser.power()
   at Pytocs.Core.Syntax.Parser.factor()
   at Pytocs.Core.Syntax.Parser.term()
   at Pytocs.Core.Syntax.Parser.arith_expr()
   at Pytocs.Core.Syntax.Parser.shift_expr()
   at Pytocs.Core.Syntax.Parser.and_expr()
   at Pytocs.Core.Syntax.Parser.xor_expr()
   at Pytocs.Core.Syntax.Parser.expr()
   at Pytocs.Core.Syntax.Parser.comparison()
   at Pytocs.Core.Syntax.Parser.not_test()
   at Pytocs.Core.Syntax.Parser.and_test()
   at Pytocs.Core.Syntax.Parser.or_test()
   at Pytocs.Core.Syntax.Parser.test()
   at Pytocs.Core.Syntax.Parser.testlist_star_expr()
   at Pytocs.Core.Syntax.Parser.expr_stmt()
   at Pytocs.Core.Syntax.Parser.small_stmt()
   at Pytocs.Core.Syntax.Parser.simple_stmt()
   at Pytocs.Core.Syntax.Parser.stmt()
   at Pytocs.Core.Syntax.Parser.suite()
   at Pytocs.Core.Syntax.Parser.funcdef()
   at Pytocs.Core.Syntax.Parser.compound_stmt()
   at Pytocs.Core.Syntax.Parser.stmt()
   at Pytocs.Core.Syntax.Parser.<Parse>d__4.MoveNext()
   at Pytocs.Core.Translate.ModuleTranslator.Translate(IEnumerable`1 statements)
   at Pytocs.Core.Translator.TranslateModuleStatements(IEnumerable`1 stm, TypeReferenceTranslator types, TextWriter output)
   at Pytocs.Core.Translator.TranslateFile(String inputFileName, String outputFileName)
   at Pytocs.Cli.Program.Main(String[] args)

```

**Comment by Nucs** [comment]
In my opinion, `kwargs` should be treated as `Dictionary<string,object>` and merged via `Dictionary<>.AddRange(...)` to `dictionary`.

Edit:
Hashtable as it is now works well too.

**Comment by uxmal** [comment]
I've chose to add a method `DictionaryUtils.Unpack` to `pytocs.runtime` to perform the unpacking that `**kwargs` does. The resulting code for your sample is:
```C#
public static class foo {

    public static object funcy(Hashtable kwargs, params object [] args) {
        var dictionary = DictionaryUtils.Unpack(("a", "str"), kwargs);
        var dictionary_inside_tuple = Tuple.Create(1, DictionaryUtils.Unpack(("a", "str"), kwargs));
        return dictionary;
    }
}
```
